import Link from 'next/link'
import React from 'react'

export default function page() {
  return (
    <div className='min-h-screen text-white flex flex-col transition-all scroll-smooth'>

        <div className='flex flex-col'>
            <h1>table of contents</h1>
            <Link href='#1'>First</Link>
            <Link href='#2'>second</Link>
            <Link href='#3'>third</Link>
            <Link href='#4'>fourth</Link>
        </div>
        
        <div className='my-20 w-[70%] mx-auto' id='1'>
            <h3 className='text-red-400'>First project</h3>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam optio, rem facere officiis tenetur quia totam, asperiores veniam reiciendis sed praesentium maiores mollitia voluptate obcaecati aspernatur, nemo illum illo. Dicta et omnis ipsa tempora saepe blanditiis nesciunt quam natus fugit dolorum nulla at ratione commodi aut culpa optio mollitia ut, dolorem enim qui eum. Assumenda, facilis? Quia recusandae adipisci accusantium similique, sed omnis ipsum modi ipsam possimus voluptates eveniet quisquam doloremque natus quas voluptate sit est unde blanditiis neque debitis cumque minima atque doloribus odio? Veritatis nam repudiandae facere obcaecati quia perferendis eaque et nihil sapiente! Placeat, hic. Sed, magnam.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eius quia obcaecati ad. Explicabo cumque blanditiis eligendi perferendis molestias, dicta autem quisquam, quo praesentium illum provident! Unde eaque tenetur, illo exercitationem repellat quos aliquid id beatae molestias praesentium, officia laborum a optio adipisci pariatur laboriosam dolores. Aliquid eveniet debitis veniam fuga iste illo cupiditate pariatur illum! Minima asperiores quae mollitia sed sint distinctio architecto facilis natus blanditiis! Nulla, a eius. Quibusdam earum reiciendis officiis? Cupiditate obcaecati sequi amet consequuntur sit temporibus. Delectus dignissimos quis saepe a at minus, dolores dolorem incidunt labore consectetur quia animi voluptatum debitis odit tempore? Unde enim maxime quis quas ullam maiores voluptas doloremque, tenetur, ex eos aliquam deserunt error amet animi, ab reprehenderit eaque sunt molestiae asperiores consectetur aliquid natus! Eveniet aliquam officia magnam. Culpa, odit reprehenderit quos aut porro dolorem incidunt rem illo itaque quibusdam nostrum veniam. Earum, ipsum mollitia aspernatur a sed nisi dolorum, reprehenderit adipisci reiciendis accusamus magni. Rem vitae possimus quaerat? Accusamus voluptate sequi quisquam quos illum rerum adipisci excepturi aliquid maiores deleniti, odit quis qui eaque? Maiores quia hic laborum! Tempora porro harum aut dolor perspiciatis soluta repellat dolores minus, magnam possimus, eum veritatis quam corrupti, quibusdam quod iure voluptate culpa est nam molestiae nemo sequi eos ratione. Aliquid, dignissimos saepe obcaecati culpa sequi dolorem omnis esse soluta odit, magni hic inventore cupiditate a alias deleniti excepturi dicta nisi earum. Necessitatibus placeat esse, porro ut reprehenderit ea nesciunt, doloribus ab sint modi omnis quod quaerat expedita amet quisquam magnam quasi illum earum? Illo facere voluptatibus, consectetur praesentium ipsum eos enim earum quam fuga atque debitis repudiandae, ut aut sed, quo veritatis adipisci. Accusamus debitis corporis eum cum autem, commodi veritatis corrupti facilis ullam minus, harum amet incidunt voluptate cupiditate necessitatibus adipisci eveniet voluptatibus hic labore a inventore maiores quam? Minima, rerum?
            </p>
        </div>
        <div className='my-20 w-[70%] mx-auto' id='2'>
            <h3 className='text-red-400'>SECOND project</h3>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam optio, rem facere officiis tenetur quia totam, asperiores veniam reiciendis sed praesentium maiores mollitia voluptate obcaecati aspernatur, nemo illum illo. Dicta et omnis ipsa tempora saepe blanditiis nesciunt quam natus fugit dolorum nulla at ratione commodi aut culpa optio mollitia ut, dolorem enim qui eum. Assumenda, facilis? Quia recusandae adipisci accusantium similique, sed omnis ipsum modi ipsam possimus voluptates eveniet quisquam doloremque natus quas voluptate sit est unde blanditiis neque debitis cumque minima atque doloribus odio? Veritatis nam repudiandae facere obcaecati quia perferendis eaque et nihil sapiente! Placeat, hic. Sed, magnam.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eius quia obcaecati ad. Explicabo cumque blanditiis eligendi perferendis molestias, dicta autem quisquam, quo praesentium illum provident! Unde eaque tenetur, illo exercitationem repellat quos aliquid id beatae molestias praesentium, officia laborum a optio adipisci pariatur laboriosam dolores. Aliquid eveniet debitis veniam fuga iste illo cupiditate pariatur illum! Minima asperiores quae mollitia sed sint distinctio architecto facilis natus blanditiis! Nulla, a eius. Quibusdam earum reiciendis officiis? Cupiditate obcaecati sequi amet consequuntur sit temporibus. Delectus dignissimos quis saepe a at minus, dolores dolorem incidunt labore consectetur quia animi voluptatum debitis odit tempore? Unde enim maxime quis quas ullam maiores voluptas doloremque, tenetur, ex eos aliquam deserunt error amet animi, ab reprehenderit eaque sunt molestiae asperiores consectetur aliquid natus! Eveniet aliquam officia magnam. Culpa, odit reprehenderit quos aut porro dolorem incidunt rem illo itaque quibusdam nostrum veniam. Earum, ipsum mollitia aspernatur a sed nisi dolorum, reprehenderit adipisci reiciendis accusamus magni. Rem vitae possimus quaerat? Accusamus voluptate sequi quisquam quos illum rerum adipisci excepturi aliquid maiores deleniti, odit quis qui eaque? Maiores quia hic laborum! Tempora porro harum aut dolor perspiciatis soluta repellat dolores minus, magnam possimus, eum veritatis quam corrupti, quibusdam quod iure voluptate culpa est nam molestiae nemo sequi eos ratione. Aliquid, dignissimos saepe obcaecati culpa sequi dolorem omnis esse soluta odit, magni hic inventore cupiditate a alias deleniti excepturi dicta nisi earum. Necessitatibus placeat esse, porro ut reprehenderit ea nesciunt, doloribus ab sint modi omnis quod quaerat expedita amet quisquam magnam quasi illum earum? Illo facere voluptatibus, consectetur praesentium ipsum eos enim earum quam fuga atque debitis repudiandae, ut aut sed, quo veritatis adipisci. Accusamus debitis corporis eum cum autem, commodi veritatis corrupti facilis ullam minus, harum amet incidunt voluptate cupiditate necessitatibus adipisci eveniet voluptatibus hic labore a inventore maiores quam? Minima, rerum?
            </p>
        </div>
        <div className='my-20 w-[70%] mx-auto' id='3'>
            <h3 className='text-red-400'>THIRD project</h3>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam optio, rem facere officiis tenetur quia totam, asperiores veniam reiciendis sed praesentium maiores mollitia voluptate obcaecati aspernatur, nemo illum illo. Dicta et omnis ipsa tempora saepe blanditiis nesciunt quam natus fugit dolorum nulla at ratione commodi aut culpa optio mollitia ut, dolorem enim qui eum. Assumenda, facilis? Quia recusandae adipisci accusantium similique, sed omnis ipsum modi ipsam possimus voluptates eveniet quisquam doloremque natus quas voluptate sit est unde blanditiis neque debitis cumque minima atque doloribus odio? Veritatis nam repudiandae facere obcaecati quia perferendis eaque et nihil sapiente! Placeat, hic. Sed, magnam.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eius quia obcaecati ad. Explicabo cumque blanditiis eligendi perferendis molestias, dicta autem quisquam, quo praesentium illum provident! Unde eaque tenetur, illo exercitationem repellat quos aliquid id beatae molestias praesentium, officia laborum a optio adipisci pariatur laboriosam dolores. Aliquid eveniet debitis veniam fuga iste illo cupiditate pariatur illum! Minima asperiores quae mollitia sed sint distinctio architecto facilis natus blanditiis! Nulla, a eius. Quibusdam earum reiciendis officiis? Cupiditate obcaecati sequi amet consequuntur sit temporibus. Delectus dignissimos quis saepe a at minus, dolores dolorem incidunt labore consectetur quia animi voluptatum debitis odit tempore? Unde enim maxime quis quas ullam maiores voluptas doloremque, tenetur, ex eos aliquam deserunt error amet animi, ab reprehenderit eaque sunt molestiae asperiores consectetur aliquid natus! Eveniet aliquam officia magnam. Culpa, odit reprehenderit quos aut porro dolorem incidunt rem illo itaque quibusdam nostrum veniam. Earum, ipsum mollitia aspernatur a sed nisi dolorum, reprehenderit adipisci reiciendis accusamus magni. Rem vitae possimus quaerat? Accusamus voluptate sequi quisquam quos illum rerum adipisci excepturi aliquid maiores deleniti, odit quis qui eaque? Maiores quia hic laborum! Tempora porro harum aut dolor perspiciatis soluta repellat dolores minus, magnam possimus, eum veritatis quam corrupti, quibusdam quod iure voluptate culpa est nam molestiae nemo sequi eos ratione. Aliquid, dignissimos saepe obcaecati culpa sequi dolorem omnis esse soluta odit, magni hic inventore cupiditate a alias deleniti excepturi dicta nisi earum. Necessitatibus placeat esse, porro ut reprehenderit ea nesciunt, doloribus ab sint modi omnis quod quaerat expedita amet quisquam magnam quasi illum earum? Illo facere voluptatibus, consectetur praesentium ipsum eos enim earum quam fuga atque debitis repudiandae, ut aut sed, quo veritatis adipisci. Accusamus debitis corporis eum cum autem, commodi veritatis corrupti facilis ullam minus, harum amet incidunt voluptate cupiditate necessitatibus adipisci eveniet voluptatibus hic labore a inventore maiores quam? Minima, rerum?
            </p>
        </div>
        <div className='my-20 w-[70%] mx-auto' id='4'>
            <h3 className='text-red-400'>FOURTH project</h3>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Quibusdam optio, rem facere officiis tenetur quia totam, asperiores veniam reiciendis sed praesentium maiores mollitia voluptate obcaecati aspernatur, nemo illum illo. Dicta et omnis ipsa tempora saepe blanditiis nesciunt quam natus fugit dolorum nulla at ratione commodi aut culpa optio mollitia ut, dolorem enim qui eum. Assumenda, facilis? Quia recusandae adipisci accusantium similique, sed omnis ipsum modi ipsam possimus voluptates eveniet quisquam doloremque natus quas voluptate sit est unde blanditiis neque debitis cumque minima atque doloribus odio? Veritatis nam repudiandae facere obcaecati quia perferendis eaque et nihil sapiente! Placeat, hic. Sed, magnam.
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eius quia obcaecati ad. Explicabo cumque blanditiis eligendi perferendis molestias, dicta autem quisquam, quo praesentium illum provident! Unde eaque tenetur, illo exercitationem repellat quos aliquid id beatae molestias praesentium, officia laborum a optio adipisci pariatur laboriosam dolores. Aliquid eveniet debitis veniam fuga iste illo cupiditate pariatur illum! Minima asperiores quae mollitia sed sint distinctio architecto facilis natus blanditiis! Nulla, a eius. Quibusdam earum reiciendis officiis? Cupiditate obcaecati sequi amet consequuntur sit temporibus. Delectus dignissimos quis saepe a at minus, dolores dolorem incidunt labore consectetur quia animi voluptatum debitis odit tempore? Unde enim maxime quis quas ullam maiores voluptas doloremque, tenetur, ex eos aliquam deserunt error amet animi, ab reprehenderit eaque sunt molestiae asperiores consectetur aliquid natus! Eveniet aliquam officia magnam. Culpa, odit reprehenderit quos aut porro dolorem incidunt rem illo itaque quibusdam nostrum veniam. Earum, ipsum mollitia aspernatur a sed nisi dolorum, reprehenderit adipisci reiciendis accusamus magni. Rem vitae possimus quaerat? Accusamus voluptate sequi quisquam quos illum rerum adipisci excepturi aliquid maiores deleniti, odit quis qui eaque? Maiores quia hic laborum! Tempora porro harum aut dolor perspiciatis soluta repellat dolores minus, magnam possimus, eum veritatis quam corrupti, quibusdam quod iure voluptate culpa est nam molestiae nemo sequi eos ratione. Aliquid, dignissimos saepe obcaecati culpa sequi dolorem omnis esse soluta odit, magni hic inventore cupiditate a alias deleniti excepturi dicta nisi earum. Necessitatibus placeat esse, porro ut reprehenderit ea nesciunt, doloribus ab sint modi omnis quod quaerat expedita amet quisquam magnam quasi illum earum? Illo facere voluptatibus, consectetur praesentium ipsum eos enim earum quam fuga atque debitis repudiandae, ut aut sed, quo veritatis adipisci. Accusamus debitis corporis eum cum autem, commodi veritatis corrupti facilis ullam minus, harum amet incidunt voluptate cupiditate necessitatibus adipisci eveniet voluptatibus hic labore a inventore maiores quam? Minima, rerum?
            </p>
        </div>
        
    </div>
  )
}
