
import { Inter,Sevillana,Silkscreen,Alkatra,DotGothic16} from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'



const inter = Inter({ subsets: ['latin'] })
export const alkatra = Alkatra({ subsets: ['latin'], weight: '400'  })
export const sevillana = Sevillana({ subsets: ['latin'], weight: '400'  })
export const silkscreen = Silkscreen({ subsets: ['latin'], weight: '400'  })
export const dotGothic16 = DotGothic16({ subsets: ['latin'], weight: '400'  })
 const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
      

        <div className='w-full h-full bg-black'>
        <div className='max-w-[110rem] scroll-smooth mx-auto'>
          <div className='main'>
        {children}
          </div>
        </div>
        </div>
        </body>
    </html>
  )
}
